### ISSUE TITLE
Factions Endermen

### ISSUE THREAD

**Issue by zach-alphabeta** [FadeCloudNW/Issues#10]
**What server(s) does this affect?**
Factions

**Describe the bug**
Enderman does not drop Enderpearls when killed by Fall Damage.

**To Reproduce**
1. Place an Endermand spawner at least 44 Blocks above the ground
2. Let the Enderman spawn and fall.
3. Watch it die.

**Expected behavior**
Nothing will Drop.

**Minecraft Info:**
 - Your current version: 1.12.2
 - Installed mods: LabyMod (Including: BetterHat, ItemPhysics, MoreParticles, OptiFine 1.12.2HDUE2)

**Comment by AlekseyTitov99** [comment]
Fixed?
