### ISSUE TITLE
Factions Ice in Nether

### ISSUE THREAD

**Issue by zach-alphabeta** [FadeCloudNW/Issues#11]
**What server(s) does this affect?**
Factions

**Describe the bug**
Placing Ice in nether than breaking it doesn't create water.

**To Reproduce**
1. Go to the Nether: `/warp nether`
2. Run /wild
3. Place Ice
4. Break the Ice
5. See error

**Expected behavior**
Water won't spawn after breaking ice

**Screenshots**
![image](https://user-images.githubusercontent.com/59401387/71638023-7a43df00-2c22-11ea-90b9-443e666d53fb.png)

**Minecraft Info:**
 - Your current version: 1.12.2
 - Installed mods: LabyMod (Including: BetterHat, ItemPhysics, MoreParticles, OptiFine 1.12.2HDUE2)

**Comment by AlekseyTitov99** [comment]
Fixed
