### ISSUE TITLE
Factions Sell Wand

### ISSUE THREAD

**Issue by zach-alphabeta** [FadeCloudNW/Issues#13]
**What server(s) does this affect?**
Factions

**Describe the bug**
If you obtain a Factions Sell Wand (A Blaze Rod), you can run the command `/sell all` and you will lose the wand. The major issue with this is players can buy it from Buycraft and get this issue, wasting 3.75 USD.

**To Reproduce**
1. Run `/sellwand give <player> 1`
2. Run `/sell all`
3. See error

**Expected behavior**
Your Sell Wand will sell as a normal blaze rod.

**Screenshots**
![image](https://user-images.githubusercontent.com/59401387/71758231-31329b80-2e6b-11ea-9b14-5372b7c5a5ce.png)
![image](https://user-images.githubusercontent.com/59401387/71758245-4f000080-2e6b-11ea-8eed-74824c69e088.png)

**Minecraft Info:**
 - Your current version: 1.12.2
 - Installed mods: LabyMod (Including: BetterHat, ItemPhysics, MoreParticles, OptiFine 1.12.2HDUE2)

**Comment by AlekseyTitov99** [comment]
Fixed
