### ISSUE TITLE
Faction Shield

### ISSUE THREAD

**Issue by zach-alphabeta** [FadeCloudNW/Issues#2]
**What server(s) does this affect?**
Factions

**Describe the bug**
Faction Shield's GUI has 3 Shield Settings, but only 2 are visible. The 3rd Option is an active slot with no visible clock. 

**To Reproduce**
1. Open the Faction Shield GUI: /f shield
2. Look at slot number 15 (In correlation to this)
![image](https://user-images.githubusercontent.com/59401387/71635728-1ce56900-2bf5-11ea-9854-07ed9bfa1cc3.png)
3. Click the Slot

**Expected behavior**
The 15th Slot is a shield option, but it does not have a visible clock

**Screenshots**
![image](https://user-images.githubusercontent.com/59401387/71635856-58ccfe00-2bf6-11ea-8482-3091d22c8b42.png)

**Minecraft Info:**
 - Your current version: 1.12.2
 - Installed mods: LabyMod (Including: BetterHat, ItemPhysics, MoreParticles, OptiFine 1.12.2HDUE2)

**Comment by tavonkelly** [comment]
Should be fixed on next Factions reboot

**Comment by zach-alphabeta** [comment]
Issue was Fixed.

Move when available.
